- name: Ansible Datatypes
  hosts: local
  connection: local
  vars:
   DURATION: 120 # Number
   COURSE: Ansible # String
   IS_LIVE: true # Boolean
   TOOLS: # List []
   - Linux
   - Shell
   - Ansible
   CONCEPTS: #Map or Dictionary or Object {}
     CI: Jenkins
     SCRIPTING: "Shell, Ansible, Terraform, Python"
  tasks:
  - name: Print Course Information
    ansible.builtin.debug:
      msg: "COURSE is: {{ COURSE }}, DURATION: {{ DURATION }}, is live?: {{ IS_LIVE }}, Tools are: {{ TOOLS }}, CONCEPTS are: {{ CONCEPTS }}"