- name: Install Packages using Loops
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: Install list of Packages
    ansible.builtin.dnf:
      name: "{{ item }}" #Here we ensure writing it in quotes
      state: installed
    loop:
    - mysql
    - nginx
