- name: Functions Demo
  hosts: local
  connection: local
  vars:
    persons: "Andrew, Brat, Chuck, David"
  tasks:
  - name: Check undefined variable
    ansible.builtin.debug:
      msg: "Hello! {{ person | default('Jessie') }} "

  - name: Print Names
    ansible.builtin.debug:
      msg: "Hello! {{ persons }}"

  - name: Print Names by splitting
    ansible.builtin.debug:
      msg: "Hello! {{ persons | split(',') }}"

  - name: Convert Map into list
    vars:
      course:
        name: DevOps
        duration: 10 hr
        trainer: Siva
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items }}"

  - name: Convert Map into list
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hr'}
      - {'key': 'trainer', 'value': 'Siva'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict }}"

  - name: Convert to Upper Case
    vars: 
      name: Naveen Kumar
    ansible.builtin.debug:
      msg: "Name: {{ name | upper }}"