- name: Shell Vs Command
  hosts: local
  connection: local
  tasks:
  - name: Redirect ls output to a file using command
    ansible.builtin.command: "ls -ltr > /tmp/output.txt"

  tasks:
  - name: Redirect ls output to a file using shell
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"