- name: Create ec2 and r53 records
  hosts: local
  connection: local
  vars: 
    instances:
      - mysql
      - backend
      - frontend
    subnet_id: subnet-05160d290859e4211
    sg_id: sg-0c05c24867a0de439
    ami_id: ami-0220d79f3f480ecf5
    zone: easydevops.fun
  tasks:
    - name: Create ec2 
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: t3.micro 
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: Print output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"


    - name: Create Route53 records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ zone if item.item == 'frontend' else item.item ~ '.' ~ zone}}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address if item.item == 'frontend' else item.instances[0].private_ip_address}}"
        overwrite: true
        wait: true
      loop: "{{ ec2_output.results }}"

