- name: Play Level Variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible
    DURATION: 10hr
    TRAINER: SivaKumar
  tasks:
  - name: Print Course Information
    ansible.builtin.debug:
      msg: "Hello {{COURSE }}! Course Duration: {{ DURATION }} and Trainer is: {{ TRAINER }}"

  - name: Print Course Information Again
    ansible.builtin.debug:
      msg: "Hello {{COURSE }}! Course Duration: {{ DURATION }} and Trainer is: {{ TRAINER }}"