- name: Task Level Variables
  hosts: local
  connection: local
  vars:
    COURSE: DevOps with AWS
    DURATION: 10hr
    TRAINER: SivaKumar
  tasks:
  - name: Print Course Information
    vars: 
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Hello {{COURSE }}! Course Duration: {{ DURATION }} and Trainer is: {{ TRAINER }}"
  
  - name: Print Course Information Again
    vars: 
      DURATION: 20hr
    ansible.builtin.debug:
      msg: "Hello {{COURSE }}! Course Duration: {{ DURATION }} and Trainer is: {{ TRAINER }}"