[frontend]
34.236.150.147 COURSE=Ansible DURATION=10hr TRAINER=SivaKumar ansible_user=ec2-user ansible_password=DevOps321
54.144.120.45  COURSE=Terraform DURATION=11hr TRAINER=SivaKumar ansible_user=ec2-user ansible_password=DevOps321

[backend]
54.144.120.45

[local]
localhost

[local:vars]
COURSE=DevOps with Siva
DURATION=30hr
TRAINER=SivaKumar