[frontend]
44.222.203.61 COURSE=Ansible DURATION=10hr TRAINER=SivaKumar ansible_user=ec2-user ansible_password=DevOps321
13.221.111.59  COURSE=Terraform DURATION=11hr TRAINER=SivaKumar ansible_user=ec2-user ansible_password=DevOps321

[backend]
13.221.111.59

[local]
localhost

[local:vars]
COURSE=DevOps with Siva
DURATION=30hr
TRAINER=SivaKumar